/* Fictional schools and clubs. Array order is part of the seeded generator: do not reorder.
   `original` keeps the first-draft name from the v0.3.1 renaming pass; later renames are logged in
   audit/renames-*.csv. Check high-school names against the real school register with
   audit/check-catalog-neis.py. */
// Ported from KBO-Draft-Room df4faad src/core/catalog.js. See docs/UPSTREAM.md.

// prettier-ignore
const institutions = [
  {"id":"hs000","name":"한양고","original":"한성고","region":"서울","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs001","name":"흥인고","original":"한국대사대부속고","region":"서울","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs002","name":"광암고","original":"광암고","region":"서울","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs003","name":"충정고","original":"충정고","region":"경기·강원","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs004","name":"서평고","original":"평택첨단고","region":"경기·강원","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs005","name":"인하고","original":"인하고","region":"인천","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs006","name":"삼랑고","original":"강화고","region":"인천","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs007","name":"북영고","original":"북영고","region":"대전·충청·전북","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs008","name":"전주일고","original":"전주일고","region":"대전·충청·전북","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs009","name":"수창고","original":"달구벌고","region":"대구·경북","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs010","name":"용지고","original":"경남중앙고","region":"경남","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs011","name":"초량고","original":"부산해사고","region":"부산·울산","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs012","name":"장산고","original":"동래고","region":"부산·울산","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs013","name":"송정고","original":"송정고","region":"광주·전남·제주","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs014","name":"무진고","original":"광주체육고","region":"광주·전남·제주","tier":"명문","kind":"high-school","country":"대한민국"},
  {"id":"hs015","name":"동곡고","original":"동곡고","region":"서울","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs016","name":"서초상업고","original":"서초상업고","region":"서울","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs017","name":"종암고","original":"서울AI고","region":"서울","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs018","name":"신영고","original":"신명고","region":"서울","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs019","name":"명강고","original":"명강고","region":"경기·강원","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs020","name":"철산고","original":"광명고","region":"경기·강원","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs021","name":"덕풍고","original":"하남하이텍고","region":"경기·강원","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs022","name":"매송고","original":"화성고","region":"경기·강원","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs023","name":"포남고","original":"강릉고","region":"경기·강원","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs024","name":"운서고","original":"영종고","region":"인천","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs025","name":"문학고","original":"미추홀예술고","region":"인천","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs026","name":"계룡BC","original":"계룡고","region":"대전·충청·전북","tier":"강호","kind":"hs-club","country":"대한민국"},
  {"id":"hs027","name":"유성BC","original":"유성고","region":"대전·충청·전북","tier":"강호","kind":"hs-club","country":"대한민국"},
  {"id":"hs028","name":"대전대영고","original":"대청고","region":"대전·충청·전북","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs029","name":"북대전고","original":"북대전고","region":"대전·충청·전북","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs030","name":"월배고","original":"달서고","region":"대구·경북","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs031","name":"장량고","original":"포항해사고","region":"대구·경북","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs032","name":"경산BC","original":"경주고BC","region":"대구·경북","tier":"강호","kind":"hs-club","country":"대한민국"},
  {"id":"hs033","name":"수성공고","original":"수성공고","region":"대구·경북","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs034","name":"미조고","original":"남해수산고","region":"경남","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs035","name":"마산봉암고","original":"마산봉암고","region":"경남","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs036","name":"상남고","original":"창원고","region":"경남","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs037","name":"주촌고","original":"김해고","region":"경남","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs038","name":"태화고","original":"태화고","region":"부산·울산","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs039","name":"해운대상업고","original":"해운대상업고","region":"부산·울산","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs040","name":"달동고","original":"울산석유화학고","region":"부산·울산","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs041","name":"임랑BC","original":"임랑BC","region":"부산·울산","tier":"강호","kind":"hs-club","country":"대한민국"},
  {"id":"hs042","name":"무등고","original":"무등고","region":"광주·전남·제주","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs043","name":"용봉고","original":"용봉고","region":"광주·전남·제주","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs044","name":"보길고","original":"다도해고","region":"광주·전남·제주","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs045","name":"조례고","original":"순천팔마고","region":"광주·전남·제주","tier":"강호","kind":"high-school","country":"대한민국"},
  {"id":"hs046","name":"염리고","original":"서울전자고","region":"서울","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs047","name":"방이고","original":"경성고","region":"서울","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs048","name":"이문고","original":"휘성고","region":"서울","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs049","name":"서울남산고","original":"서울남산고","region":"서울","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs050","name":"마포BC","original":"조은BC","region":"서울","tier":"중견","kind":"hs-club","country":"대한민국"},
  {"id":"hs051","name":"봉포고","original":"봉포고","region":"경기·강원","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs052","name":"동해고","original":"동해고","region":"경기·강원","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs053","name":"용현고","original":"용문고","region":"경기·강원","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs054","name":"지평고","original":"곤지암고","region":"경기·강원","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs055","name":"탄천고","original":"분당교통고","region":"경기·강원","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs056","name":"경서고","original":"청라고","region":"인천","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs057","name":"마전고","original":"아라빛고","region":"인천","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs058","name":"소래공고","original":"소래고","region":"인천","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs059","name":"금마고","original":"익산고","region":"대전·충청·전북","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs060","name":"전주서산고","original":"전주서산고","region":"대전·충청·전북","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs061","name":"연기고","original":"세종고","region":"대전·충청·전북","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs062","name":"한밭공고","original":"한밭공고","region":"대전·충청·전북","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs063","name":"대명가톨릭고","original":"대명고","region":"대구·경북","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs064","name":"인동고","original":"송림반도체고","region":"대구·경북","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs065","name":"용상고","original":"와룡고","region":"대구·경북","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs066","name":"웅천고","original":"진해고","region":"경남","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs067","name":"물금BC","original":"물금BC","region":"경남","tier":"중견","kind":"hs-club","country":"대한민국"},
  {"id":"hs068","name":"한려고","original":"한려고","region":"경남","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs069","name":"옥포BC","original":"옥포BC","region":"경남","tier":"중견","kind":"hs-club","country":"대한민국"},
  {"id":"hs070","name":"장생포고","original":"장생포고","region":"부산·울산","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs071","name":"영도고","original":"영도고","region":"부산·울산","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs072","name":"범천고","original":"부산진고","region":"부산·울산","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs073","name":"연산고","original":"사직체육고","region":"부산·울산","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs074","name":"돌산고","original":"돌산고","region":"광주·전남·제주","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs075","name":"광양BC","original":"광양BC","region":"광주·전남·제주","tier":"중견","kind":"hs-club","country":"대한민국"},
  {"id":"hs076","name":"운암고","original":"광주아이티고","region":"광주·전남·제주","tier":"중견","kind":"high-school","country":"대한민국"},
  {"id":"hs077","name":"망원고","original":"한국디자인고","region":"서울","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs078","name":"염창고","original":"배전고","region":"서울","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs079","name":"성명고","original":"성명고","region":"서울","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs080","name":"노원BC","original":"한웅BC","region":"서울","tier":"약소","kind":"hs-club","country":"대한민국"},
  {"id":"hs081","name":"화촌고","original":"단오고","region":"경기·강원","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs082","name":"김포BC","original":"김포BC","region":"경기·강원","tier":"약소","kind":"hs-club","country":"대한민국"},
  {"id":"hs083","name":"적성고","original":"신월고","region":"경기·강원","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs084","name":"인천남동공고","original":"인천남동고","region":"인천","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs085","name":"만석고","original":"월미해양고","region":"인천","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs086","name":"도연고","original":"도안고","region":"대전·충청·전북","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs087","name":"청원BC","original":"청주고BC","region":"대전·충청·전북","tier":"약소","kind":"hs-club","country":"대한민국"},
  {"id":"hs088","name":"충주호암고","original":"충주상고","region":"대전·충청·전북","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs089","name":"문경고","original":"문경고","region":"대구·경북","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs090","name":"동대구고","original":"동대구고","region":"대구·경북","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs091","name":"칠곡BC","original":"선덕BC","region":"대구·경북","tier":"약소","kind":"hs-club","country":"대한민국"},
  {"id":"hs092","name":"가야BC","original":"가야BC","region":"경남","tier":"약소","kind":"hs-club","country":"대한민국"},
  {"id":"hs093","name":"사천공고","original":"사천공고","region":"경남","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs094","name":"진주문산고","original":"진주문산고","region":"경남","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs095","name":"합포고","original":"합포상명고","region":"경남","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs096","name":"반송고","original":"장산고","region":"부산·울산","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs097","name":"대송고","original":"부울대부속고","region":"부산·울산","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs098","name":"일광고","original":"부산대중문화예술고","region":"부산·울산","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"hs099","name":"남포BC","original":"남포BC","region":"부산·울산","tier":"약소","kind":"hs-club","country":"대한민국"},
  {"id":"hs100","name":"여수BC","original":"이순신BC","region":"광주·전남·제주","tier":"약소","kind":"hs-club","country":"대한민국"},
  {"id":"hs101","name":"영산BC","original":"영산고","region":"광주·전남·제주","tier":"약소","kind":"hs-club","country":"대한민국"},
  {"id":"hs102","name":"용해고","original":"목포공고","region":"광주·전남·제주","tier":"약소","kind":"high-school","country":"대한민국"},
  {"id":"uni00","name":"숭인대","original":"한국대","region":"서울","tier":"명문","kind":"college","country":"대한민국"},
  {"id":"uni01","name":"혜화대","original":"연서대","region":"서울","tier":"명문","kind":"college","country":"대한민국"},
  {"id":"uni02","name":"명성대","original":"명성대","region":"경기·강원","tier":"명문","kind":"college","country":"대한민국"},
  {"id":"uni03","name":"팔공대","original":"성운대","region":"대구·경북","tier":"강호","kind":"college","country":"대한민국"},
  {"id":"uni04","name":"계양대","original":"인천외국어대","region":"인천","tier":"강호","kind":"college","country":"대한민국"},
  {"id":"uni05","name":"촉석대","original":"동남대","region":"경남","tier":"강호","kind":"college","country":"대한민국"},
  {"id":"uni06","name":"금정대","original":"동성대","region":"부산·울산","tier":"강호","kind":"college","country":"대한민국"},
  {"id":"uni07","name":"청명대","original":"청명대","region":"경기·강원","tier":"중견","kind":"college","country":"대한민국"},
  {"id":"uni08","name":"대곡대","original":"대곡대","region":"대전·충청·전북","tier":"중견","kind":"college","country":"대한민국"},
  {"id":"uni09","name":"양림대","original":"광주첨단과학대","region":"광주·전남·제주","tier":"중견","kind":"college","country":"대한민국"},
  {"id":"uni10","name":"계룡대","original":"계룡대","region":"대전·충청·전북","tier":"중견","kind":"college","country":"대한민국"},
  {"id":"uni11","name":"주안대","original":"인천대","region":"인천","tier":"중견","kind":"college","country":"대한민국"},
  {"id":"uni12","name":"서귀포대","original":"서귀포대","region":"광주·전남·제주","tier":"약소","kind":"college","country":"대한민국"},
  {"id":"uni13","name":"노원대","original":"한국사이버대","region":"서울","tier":"약소","kind":"college","country":"대한민국"},
  {"id":"uni14","name":"단원대","original":"안산대","region":"경기·강원","tier":"약소","kind":"college","country":"대한민국"},
  {"id":"uni15","name":"웅진대","original":"한국축산대","region":"대전·충청·전북","tier":"약소","kind":"college","country":"대한민국"},
  {"id":"ind00","name":"김포 블랙팬서즈","original":"김포 블랙팬서즈","region":"경기·강원","tier":null,"kind":"independent","country":"대한민국"},
  {"id":"ind01","name":"하남 워리어즈","original":"하남 워리어즈","region":"경기·강원","tier":null,"kind":"independent","country":"대한민국"},
  {"id":"ind02","name":"부천 브레이브스","original":"부천 브레이브스","region":"경기·강원","tier":null,"kind":"independent","country":"대한민국"},
  {"id":"ind03","name":"안산 데블스","original":"안산 데블스","region":"경기·강원","tier":null,"kind":"independent","country":"대한민국"},
  {"id":"ov00","name":"미국 노스스타주립대","original":"미국 미네소타공대","region":null,"tier":null,"kind":"overseas-college","country":"미국","weight":15,"academicStartMonth":9,"academicEndMonth":6},
  {"id":"ov01","name":"미국 스탠리대","original":"미국 스탠리대","region":null,"tier":null,"kind":"overseas-college","country":"미국","weight":15,"academicStartMonth":9,"academicEndMonth":6},
  {"id":"ov02","name":"미국 레이크빌대","original":"미국 레이크빌대","region":null,"tier":null,"kind":"overseas-college","country":"미국","weight":15,"academicStartMonth":9,"academicEndMonth":6},
  {"id":"ov03","name":"미국 하버포인트대","original":"미국 포틀랜드대","region":null,"tier":null,"kind":"overseas-college","country":"미국","weight":15,"academicStartMonth":9,"academicEndMonth":6},
  {"id":"ov04","name":"미국 그랜드리버대","original":"미국 뉴멕시코주립대","region":null,"tier":null,"kind":"overseas-college","country":"미국","weight":15,"academicStartMonth":9,"academicEndMonth":6},
  {"id":"ov05","name":"캐나다 레이크쇼어대","original":"캐나다 토론토공대","region":null,"tier":null,"kind":"overseas-college","country":"캐나다","weight":15,"academicStartMonth":9,"academicEndMonth":6},
  {"id":"ov06","name":"일본 도난산업대","original":"일본 하네다대","region":null,"tier":null,"kind":"overseas-college","country":"일본","weight":2,"academicStartMonth":4,"academicEndMonth":3},
  {"id":"ov07","name":"일본 사가미국제대","original":"일본 미나미도쿄대","region":null,"tier":null,"kind":"overseas-college","country":"일본","weight":2,"academicStartMonth":4,"academicEndMonth":3},
  {"id":"ov08","name":"대만 중부과기대","original":"대만 타이중공대","region":null,"tier":null,"kind":"overseas-college","country":"대만","weight":2,"academicStartMonth":9,"academicEndMonth":6},
  // V0.6 additions (fictional)
  {"id":"hs106","name":"서울청운고","region":"서울","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs107","name":"강서BC","region":"서울","tier":"약소","kind":"hs-club","country":"대한민국","fictional":true},
  {"id":"hs108","name":"진주남강고","region":"경남","tier":"강호","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs109","name":"고현고","region":"경남","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs110","name":"성거고","region":"대전·충청·전북","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs111","name":"완주BC","region":"대전·충청·전북","tier":"약소","kind":"hs-club","country":"대한민국","fictional":true},
  {"id":"hs112","name":"감천고","region":"부산·울산","tier":"강호","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs113","name":"호계고","region":"부산·울산","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs114","name":"송현고","region":"인천","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs115","name":"부평BC","region":"인천","tier":"약소","kind":"hs-club","country":"대한민국","fictional":true},
  {"id":"hs116","name":"후평고","region":"경기·강원","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs117","name":"구운고","region":"경기·강원","tier":"강호","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs118","name":"안계고","region":"대구·경북","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs119","name":"달성BC","region":"대구·경북","tier":"약소","kind":"hs-club","country":"대한민국","fictional":true},
  {"id":"hs120","name":"남평고","region":"광주·전남·제주","tier":"강호","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs121","name":"애월BC","region":"광주·전남·제주","tier":"중견","kind":"hs-club","country":"대한민국","fictional":true},
  {"id":"uni16","name":"치악대","region":"경기·강원","tier":"중견","kind":"college","country":"대한민국","fictional":true},
  {"id":"uni17","name":"상당대","region":"대전·충청·전북","tier":"약소","kind":"college","country":"대한민국","fictional":true},
  {"id":"uni18","name":"금관대","region":"경남","tier":"강호","kind":"college","country":"대한민국","fictional":true},
  {"id":"uni19","name":"삼다대","region":"광주·전남·제주","tier":"중견","kind":"college","country":"대한민국","fictional":true},
  {"id":"ind04","name":"춘천 레이크폭스","region":"경기·강원","tier":null,"kind":"independent","country":"대한민국","fictional":true},
  {"id":"ind05","name":"청주 그린호크스","region":"대전·충청·전북","tier":null,"kind":"independent","country":"대한민국","fictional":true},
  {"id":"pro00","name":"리버시티 트레일스","level":"A","kind":"overseas-pro","country":"미국","region":null,"tier":null,"fictional":true},
  {"id":"pro01","name":"레이크뷰 폭스","level":"AA","kind":"overseas-pro","country":"미국","region":null,"tier":null,"fictional":true},
  {"id":"pro02","name":"퍼시픽 하버스","level":"AAA","kind":"overseas-pro","country":"미국","region":null,"tier":null,"fictional":true},
  {"id":"pro03","name":"메트로 코멧츠","level":"MLB","kind":"overseas-pro","country":"미국","region":null,"tier":null,"fictional":true},
  {"id":"pro04","name":"데저트 파이오니어스","level":"해외 독립","kind":"overseas-independent","country":"미국","region":null,"tier":null,"fictional":true},
  {"id":"pro05","name":"캐니언 썬버즈","level":"해외 독립","kind":"overseas-independent","country":"미국","region":null,"tier":null,"fictional":true},
  // V0.7 additions for the 400-player pool (fictional)
  {"id":"hs122","name":"신답고","region":"서울","tier":"강호","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs123","name":"응암고","region":"서울","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs124","name":"청파고","region":"서울","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs125","name":"효창고","region":"서울","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs126","name":"번동고","region":"서울","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs127","name":"금곡고","region":"경기·강원","tier":"강호","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs128","name":"운양고","region":"경기·강원","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs129","name":"호원고","region":"경기·강원","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs130","name":"내촌고","region":"경기·강원","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs131","name":"묵호고","region":"경기·강원","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs132","name":"부개고","region":"인천","tier":"강호","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs133","name":"간석고","region":"인천","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs134","name":"청천고","region":"인천","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs135","name":"석남고","region":"인천","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs136","name":"영흥고","region":"인천","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs137","name":"갈마고","region":"대전·충청·전북","tier":"강호","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs138","name":"가수원고","region":"대전·충청·전북","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs139","name":"봉명고","region":"대전·충청·전북","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs140","name":"모현고","region":"대전·충청·전북","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs141","name":"나운고","region":"대전·충청·전북","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs142","name":"만촌고","region":"대구·경북","tier":"강호","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs143","name":"범물고","region":"대구·경북","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs144","name":"칠성고","region":"대구·경북","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs145","name":"해평고","region":"대구·경북","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs146","name":"황성고","region":"대구·경북","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs147","name":"가음정고","region":"경남","tier":"강호","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs148","name":"내서고","region":"경남","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs149","name":"동읍고","region":"경남","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs150","name":"삼방고","region":"경남","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs151","name":"도남고","region":"경남","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs152","name":"광안고","region":"부산·울산","tier":"강호","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs153","name":"명장고","region":"부산·울산","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs154","name":"온산고","region":"부산·울산","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs155","name":"화봉고","region":"부산·울산","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs156","name":"덕천고","region":"부산·울산","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs157","name":"풍암고","region":"광주·전남·제주","tier":"강호","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs158","name":"쌍촌고","region":"광주·전남·제주","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs159","name":"신가고","region":"광주·전남·제주","tier":"중견","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs160","name":"오림고","region":"광주·전남·제주","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs161","name":"노형고","region":"광주·전남·제주","tier":"약소","kind":"high-school","country":"대한민국","fictional":true},
  {"id":"hs162","name":"은평BC","region":"서울","tier":"중견","kind":"hs-club","country":"대한민국","fictional":true},
  {"id":"hs163","name":"일산BC","region":"경기·강원","tier":"중견","kind":"hs-club","country":"대한민국","fictional":true},
  {"id":"hs164","name":"연수BC","region":"인천","tier":"약소","kind":"hs-club","country":"대한민국","fictional":true},
  {"id":"hs165","name":"둔산BC","region":"대전·충청·전북","tier":"중견","kind":"hs-club","country":"대한민국","fictional":true},
  {"id":"hs166","name":"수성BC","region":"대구·경북","tier":"약소","kind":"hs-club","country":"대한민국","fictional":true},
  {"id":"hs167","name":"마산BC","region":"경남","tier":"약소","kind":"hs-club","country":"대한민국","fictional":true},
  {"id":"hs168","name":"기장BC","region":"부산·울산","tier":"중견","kind":"hs-club","country":"대한민국","fictional":true},
  {"id":"hs169","name":"순천BC","region":"광주·전남·제주","tier":"약소","kind":"hs-club","country":"대한민국","fictional":true},
  {"id":"uni20","name":"성곡대","region":"서울","tier":"강호","kind":"college","country":"대한민국","fictional":true},
  {"id":"uni21","name":"한탄대","region":"경기·강원","tier":"중견","kind":"college","country":"대한민국","fictional":true},
  {"id":"uni22","name":"부평대","region":"인천","tier":"약소","kind":"college","country":"대한민국","fictional":true},
  {"id":"uni23","name":"보문대","region":"대전·충청·전북","tier":"강호","kind":"college","country":"대한민국","fictional":true},
  {"id":"uni24","name":"비슬대","region":"대구·경북","tier":"중견","kind":"college","country":"대한민국","fictional":true},
  {"id":"uni25","name":"황령대","region":"부산·울산","tier":"중견","kind":"college","country":"대한민국","fictional":true},
  {"id":"uni26","name":"무학대","region":"경남","tier":"약소","kind":"college","country":"대한민국","fictional":true},
  {"id":"uni27","name":"월출대","region":"광주·전남·제주","tier":"중견","kind":"college","country":"대한민국","fictional":true},
  {"id":"jc00","name":"노들과학대","region":"서울","tier":"강호","kind":"college2","country":"대한민국","fictional":true},
  {"id":"jc01","name":"광교정보대","region":"경기·강원","tier":"강호","kind":"college2","country":"대한민국","fictional":true},
  {"id":"jc02","name":"계산과학대","region":"인천","tier":"중견","kind":"college2","country":"대한민국","fictional":true},
  {"id":"jc03","name":"유등과학대","region":"대전·충청·전북","tier":"중견","kind":"college2","country":"대한민국","fictional":true},
  {"id":"jc04","name":"금호강정보대","region":"대구·경북","tier":"중견","kind":"college2","country":"대한민국","fictional":true},
  {"id":"jc05","name":"낙동과학대","region":"부산·울산","tier":"강호","kind":"college2","country":"대한민국","fictional":true},
  {"id":"jc06","name":"진해과학대","region":"경남","tier":"약소","kind":"college2","country":"대한민국","fictional":true},
  {"id":"jc07","name":"영산강정보대","region":"광주·전남·제주","tier":"약소","kind":"college2","country":"대한민국","fictional":true},
  {"id":"ind06","name":"고양 스트라이커스","region":"경기·강원","tier":null,"kind":"independent","country":"대한민국","fictional":true},
  {"id":"ind07","name":"인천 씨호크스","region":"인천","tier":null,"kind":"independent","country":"대한민국","fictional":true},
  {"id":"ind08","name":"세종 블루윙스","region":"대전·충청·전북","tier":null,"kind":"independent","country":"대한민국","fictional":true},
  {"id":"ind09","name":"양산 타이드","region":"경남","tier":null,"kind":"independent","country":"대한민국","fictional":true},
  {"id":"ov09","name":"미국 파인릿지대","region":null,"tier":null,"kind":"overseas-college","country":"미국","weight":10,"academicStartMonth":9,"academicEndMonth":6,"fictional":true},
  {"id":"ov10","name":"미국 레드클레이대","region":null,"tier":null,"kind":"overseas-college","country":"미국","weight":10,"academicStartMonth":9,"academicEndMonth":6,"fictional":true},
  {"id":"ov11","name":"일본 오미국제대","region":null,"tier":null,"kind":"overseas-college","country":"일본","weight":10,"academicStartMonth":4,"academicEndMonth":3,"fictional":true},
  {"id":"ohs00","name":"일본 미나토국제고","region":null,"tier":null,"kind":"overseas-hs","country":"일본","fictional":true},
  {"id":"ohs01","name":"일본 호쿠요학원고","region":null,"tier":null,"kind":"overseas-hs","country":"일본","fictional":true},
  {"id":"ohs02","name":"일본 기타하마고","region":null,"tier":null,"kind":"overseas-hs","country":"일본","fictional":true},
  {"id":"ohs03","name":"미국 레드우드아카데미","region":null,"tier":null,"kind":"overseas-hs","country":"미국","fictional":true},
  {"id":"pro06","name":"파인밸리 호크스","level":"A","kind":"overseas-pro","country":"미국","region":null,"tier":null,"fictional":true},
  {"id":"pro07","name":"콜드스프링 라이더스","level":"AA","kind":"overseas-pro","country":"미국","region":null,"tier":null,"fictional":true},
  {"id":"pro08","name":"캐피털 시그널스","level":"AAA","kind":"overseas-pro","country":"미국","region":null,"tier":null,"fictional":true},
  {"id":"pro09","name":"나니와 펠리컨스","level":"NPB 2군","kind":"overseas-pro","country":"일본","region":null,"tier":null,"fictional":true},
  {"id":"pro10","name":"타이난 라이트닝","level":"CPBL","kind":"overseas-pro","country":"대만","region":null,"tier":null,"fictional":true},
  {"id":"pro11","name":"코아우일라 스콜피온스","level":"LMB","kind":"overseas-pro","country":"멕시코","region":null,"tier":null,"fictional":true},
  {"id":"pro12","name":"골드코스트 서퍼스","level":"ABL","kind":"overseas-pro","country":"호주","region":null,"tier":null,"fictional":true},
  {"id":"pro13","name":"산인 드래곤플라이즈","level":"해외 독립","kind":"overseas-independent","country":"일본","region":null,"tier":null,"fictional":true},
];
const api = { institutions, byId: Object.fromEntries(institutions.map((x) => [x.id, x])) };
export default api;
